'use strict';
const $=s=>document.querySelector(s), U=window.UNITS, KEY='deutsch-a1-coach-v1';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fresh=()=>({version:1,scores:{},cards:{},days:[],lastUnit:0});
let state;try{state=JSON.parse(localStorage.getItem(KEY))||fresh()}catch{state=fresh()}
if(!valid(state))state=fresh();
function valid(s){return s&&s.version===1&&s.scores&&typeof s.scores==='object'&&s.cards&&typeof s.cards==='object'&&Array.isArray(s.days)&&s.days.length<10000&&s.days.every(x=>/^\d{4}-\d{2}-\d{2}$/.test(x))&&(!s.reading||(s.reading&&Number.isInteger(s.reading.pdf)&&s.reading.pdf>=1&&s.reading.pdf<=258&&s.reading.done&&s.reading.notes&&Object.entries(s.reading.done).every(([k,v])=>/^\d+$/.test(k)&&+k>=1&&+k<=258&&typeof v==='boolean')&&Object.entries(s.reading.notes).every(([k,v])=>/^\d+$/.test(k)&&+k>=1&&+k<=258&&typeof v==='string'&&v.length<=6000)))&&Number.isInteger(s.lastUnit)&&s.lastUnit>=0&&s.lastUnit<U.length&&Object.entries(s.scores).every(([k,v])=>/^\d+$/.test(k)&&+k<U.length&&Number.isFinite(v)&&v>=0&&v<=100)&&Object.entries(s.cards).every(([k,v])=>/^\d+-\d+$/.test(k)&&v&&Number.isFinite(v.due)&&Number.isFinite(v.interval)&&v.interval>=0&&v.interval<=365&&typeof v.mastered==='boolean')}
function save(activity=false){if(activity&&!state.days.includes(today()))state.days.push(today());try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('La sauvegarde locale est indisponible. Exporte ta progression.')}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4000)}
function streak(){let n=0,d=new Date();if(!state.days.includes(today()))d.setDate(d.getDate()-1);for(let i=0;i<10000;i++){let s=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(!state.days.includes(s))break;n++;d.setDate(d.getDate()-1)}return n}
const allCards=()=>U.flatMap(u=>u.vocab.map((v,i)=>({...v,key:`${u.id}-${i}`,unit:u.id})));
const dueCards=()=>allCards().filter(c=>state.cards[c.key]&&state.cards[c.key].due<=Date.now());
const pct=()=>Math.round(Object.values(state.scores).reduce((a,b)=>a+b,0)/U.length);
const mastered=()=>Object.values(state.cards).filter(c=>c.mastered).length;
let view='home', unit=0, tab='understand', quiz=null, flash=null, listening=null, installPrompt=null, recorder=null, stream=null, recordUrl=null;
const navs=[['reader','▣','Manuel'],['home','⌂','Accueil'],['courses','▤','Cours'],['speak','◇','Parler'],['listen','♫','Écouter'],['memory','▦','Réviser'],['exercise','✎','Exercices'],['progress','◉','Progrès']];
function go(v,id){location.hash=v+(id!==undefined?'/'+id:'')}
function shell(){ $('#nav').innerHTML=navs.map(([v,ic,label])=>`<a href="#${v}" class="${view===v?'active':''}" ${view===v?'aria-current="page"':''}><span class="symbol" aria-hidden="true">${ic}</span>${label}</a>`).join('');$('#breadcrumb').textContent=navs.find(x=>x[0]===view)?.[2]||'Mon cours';}
function phrase(v){return `<div class="phrase"><div><strong lang="de">${esc(v.de)}</strong><p>${esc(v.fr)}</p></div><button class="sound" data-say="${esc(v.de)}" aria-label="Écouter ${esc(v.de)}">Écouter</button></div>`}
function audioNotice(){return `<p class="notice">Voix de synthèse allemande. Hors ligne : installe une voix allemande sur ton appareil. Les enregistrements du manuel ne sont pas inclus.</p>`}
function picker(){return `<label for="unit-select">Choisir une unité</label><br><select id="unit-select">${U.map(u=>`<option value="${u.id}" ${u.id===unit?'selected':''}>${u.id===0?'Introduction':'Unité '+u.id} · ${esc(u.title)}</option>`).join('')}</select>`}
function render(){shell();let html='';const u=U[unit];
if(view==='reader'){html=renderReader()}
else if(view==='home'){const next=U.find(x=>(state.scores[x.id]||0)<80)||U[state.lastUnit];html=`<div class="eyebrow">DE PETITS PAS, CHAQUE JOUR</div><h1>Guten Tag, Oswaldo.</h1><p class="sub">Ton allemand commence ici. Une séance de 15 minutes suffit pour avancer.</p><div class="card resume-card"><div><strong>Mon manuel page par page</strong><p>Reprends au PDF p. ${state.reading?.pdf||10} — ton dernier repère.</p></div><button data-go="reader/${state.reading?.pdf||10}">Reprendre mon cours</button></div><div class="grid stats"><div class="card stat"><strong>${pct()} %</strong><span>Progression du parcours</span></div><div class="card stat"><strong>${streak()}</strong><span>Jours de suite</span></div><div class="card stat"><strong>${mastered()}</strong><span>Expressions retenues</span></div></div><div class="two"><section class="card hero"><span class="eyebrow">TA PROCHAINE LEÇON · 15 MIN</span><h2>${esc(next.title)}</h2><p>${esc(next.goal)}</p><button data-go="courses/${next.id}">Commencer ma leçon</button></section><section class="card"><span class="eyebrow">RÉVISION DU JOUR</span><h2 style="margin-top:14px">${dueCards().length} carte${dueCards().length>1?'s':''} à revoir</h2><p class="muted">Les expressions difficiles reviennent plus tôt. Les autres attendent quelques jours.</p><button data-go="memory">Faire ma révision</button></section></div><h2 class="section-title">Ta routine en 7 étapes</h2><section class="card"><p>Comprendre · Écouter · Répéter · Mémoriser · Utiliser · Tester · Réviser</p><p class="muted">Commence par une explication courte. Dis chaque phrase à voix haute, puis réutilise-la dans une situation réelle.</p><div class="progress"><div style="width:${pct()}%"></div></div><span>${Object.values(state.scores).filter(x=>x>=80).length} étapes validées sur 13</span></section>`}
else if(view==='courses'&&!location.hash.includes('/')){html=`<div class="eyebrow">INTRODUCTION + 12 UNITÉS</div><h1>Ton parcours A1</h1><p class="sub">Avance à ton rythme. Toutes les unités restent accessibles.</p><div class="grid units">${U.map(x=>`<article class="card unit"><div class="line"><span class="pill">${x.id===0?'Introduction':'Unité '+String(x.id).padStart(2,'0')}</span><small>Manuel · p. ${x.page}</small></div><h2>${esc(x.title)}</h2><h3>${esc(x.fr)}</h3><p>${esc(x.goal)}</p><div class="progress"><div style="width:${state.scores[x.id]||0}%"></div></div><small>${state.scores[x.id]===undefined?'À découvrir':'Meilleur test : '+state.scores[x.id]+' %'}</small><button data-go="courses/${x.id}">Ouvrir la leçon</button></article>`).join('')}</div>`}
else if(view==='courses'){html=`<span class="eyebrow">${unit===0?'INTRODUCTION':'UNITÉ '+unit} · MANUEL P. ${u.page}</span><h1>${esc(u.title)}</h1><p class="sub">${esc(u.goal)}</p><div class="tabs" role="group" aria-label="Étapes de la leçon">${[['understand','① Comprendre'],['vocab','② Écouter'],['repeat','③ Répéter'],['memorize','④ Mémoriser'],['use','⑤ Utiliser'],['test','⑥ Tester'],['review','⑦ Réviser']].map(([t,l])=>`<button data-tab="${t}" class="${tab===t?'active':''}">${l}</button>`).join('')}</div><section class="card">`;
if(tab==='understand')html+=`<h2>Une règle, des phrases utiles</h2><p>${esc(u.grammar)}</p>${u.more.map(m=>`<h3>${esc(m.title)}</h3><p>${esc(m.text)}</p>`).join('')}<h3>Observe et comprends</h3>${u.vocab.slice(0,3).map(phrase).join('')}<div class="notice">Méthode : lis la phrase allemande, comprends le sens, cache la traduction et redis-la.</div><button data-tab="vocab">Passer à l’écoute</button>`;
if(tab==='vocab')html+=`<h2>Ton vocabulaire essentiel</h2>${audioNotice()}${u.vocab.map(phrase).join('')}<div class="actions"><button data-tab="repeat">Travailler la prononciation</button></div>`;
if(tab==='repeat')html+=`<h2>Écoute, puis répète</h2><p>${esc(u.pron)}</p>${audioNotice()}${u.vocab.slice(0,4).map(phrase).join('')}<div class="notice">Écoute une phrase trois fois : une fois pour le sens, une fois pour les sons, une fois avant de la répéter sans regarder.</div><button data-go="speak/${unit}">Pratiquer à voix haute</button>`;
if(tab==='memorize')html+=`<h2>Retenir sans tout relire</h2><p>Essaie de retrouver la traduction avant de retourner la carte. Choisis ensuite « À revoir » ou « Je savais ».</p><button data-flash="${unit}">Réviser les 8 cartes</button>`;
if(tab==='use')html+=`<h2>Dialogue en situation</h2><div class="dialog">${u.dialog.map(phrase).join('')}</div><div class="notice"><strong>Ta mission :</strong> ${esc(u.mission)}</div><button data-go="speak/${unit}">Jouer le dialogue</button>`;
if(tab==='test')html+=`<h2>Vérifie tes acquis</h2><p>Six questions : compréhension, grammaire, traduction et ordre des mots. Valide cette étape à partir de 80 %.</p><button data-quiz="${unit}">Commencer le test</button>`;
if(tab==='review')html+=`<h2>Revoir au bon moment</h2><p>Après une bonne réponse, une carte revient après 1, 3, 7, 14 puis 30 jours. Une difficulté la fait revenir immédiatement, puis le lendemain après une bonne réponse.</p><button data-go="memory">Voir mes révisions</button>`;
html+='</section>'}
else if(view==='speak'){html=`<h1>Parler dès aujourd’hui</h1><p class="sub">Joue les deux rôles. Puis remplace les informations par les tiennes.</p>${picker()}${audioNotice()}<section class="card dialog" style="margin-top:20px"><h2>${esc(u.fr)}</h2>${u.dialog.map(phrase).join('')}<div class="notice"><strong>À toi :</strong> ${esc(u.mission)}</div><details><summary>Aide pour préparer ta réponse</summary><p>Réutilise les mots de la leçon. Fais deux ou trois phrases simples. Répète sans lire, puis compare avec les exemples.</p>${u.vocab.slice(0,3).map(phrase).join('')}</details><h3>Écoute ta propre prononciation</h3><p class="muted">Enregistrement local, sans note automatique. Compare ton rythme à la voix allemande.</p><div class="actions"><button id="record">M’enregistrer</button><button id="stop-record" class="quiet" disabled>Arrêter</button></div><div id="recording" role="status"></div></section>`}
else if(view==='listen'){html=`<h1>Comprendre à l’oreille</h1><p class="sub">Écoute sans lire l’allemand, puis choisis le sens.</p>${picker()}${audioNotice()}<section class="card" style="margin-top:22px"><h2>Une phrase, un sens</h2>${listening?listenBody():`<p>Huit phrases à écouter dans cette unité. Tu peux réécouter autant que nécessaire.</p><button id="start-listen">Commencer l’écoute</button>`}</section>`}
else if(view==='memory'){if(!flash)html=`<h1>Réviser pour retenir</h1><p class="sub">Cherche la réponse dans ta mémoire avant de retourner la carte.</p><div class="grid stats"><div class="card stat"><strong>${dueCards().length}</strong><span>À revoir aujourd’hui</span></div><div class="card stat"><strong>${mastered()}</strong><span>Connues, à entretenir</span></div><div class="card stat"><strong>${allCards().length}</strong><span>Expressions du parcours</span></div></div><div class="card" style="margin-top:22px"><h2>Ta séance</h2><div class="actions"><button id="due-review">Réviser les cartes dues</button><button class="quiet" id="new-review">Découvrir 10 cartes</button></div><p class="muted">« Je savais » planifie le prochain rappel. « À revoir » replace la carte à la fin de la séance.</p><h3>Une unité au choix</h3>${picker()}<div class="actions"><button data-flash="${unit}">Réviser cette unité</button></div></div>`;else html=flashBody()}
else if(view==='exercise'){html=`<h1>Pratiquer et se tester</h1><p class="sub">Une erreur est une indication de ce qu’il faut revoir.</p>${picker()}<section class="card" style="margin-top:22px">${quiz?quizBody():`<h2>Test · ${esc(u.title)}</h2><p>Six questions avec correction expliquée. Ton meilleur score est conservé.</p><button data-quiz="${unit}">Commencer</button>`}</section>${!quiz?`<h2 class="section-title">Trois bilans du parcours</h2><div class="grid">${[[1,4],[5,8],[9,12]].map((r,i)=>`<section class="card"><h3>Bilan ${i+1}</h3><p>Unités ${r[0]} à ${r[1]} · 12 questions</p><button data-bilan="${i}">Faire le bilan</button></section>`).join('')}</div><section class="card" style="margin-top:22px"><h2>Entraînement global A1</h2><p>24 questions de révision, puis deux missions d’expression. Ce quiz pédagogique n’est pas une reproduction des épreuves officielles.</p><button id="global-test">Faire le test global</button><details><summary>Missions d’expression écrite et orale</summary><p>Écrit : rédige un message de 30 à 40 mots pour proposer un rendez-vous. Indique le jour, l’heure et le lieu.</p><p>Oral : présente-toi en cinq phrases, commande une boisson et demande ton chemin. Vérifie : message compréhensible, verbes conjugués, mots utiles, formule de politesse.</p></details></section>`:''}`}
else if(view==='progress'){html=`<h1>Mes progrès</h1><p class="sub">Les scores reflètent les tests du coach. Ils ne constituent pas une certification A1.</p><div class="grid stats"><div class="card stat"><strong>${pct()} %</strong><span>Moyenne du parcours</span></div><div class="card stat"><strong>${state.days.length}</strong><span>Jours pratiqués</span></div><div class="card stat"><strong>${mastered()}</strong><span>Expressions connues</span></div></div><section class="card" style="margin-top:22px"><h2>Scores par unité</h2>${U.map(x=>`<div class="score-row"><div class="line"><a href="#courses/${x.id}">${esc(x.title)}</a><strong>${state.scores[x.id]===undefined?'Non testé':state.scores[x.id]+' %'}</strong></div><div class="progress"><div style="width:${state.scores[x.id]||0}%"></div></div></div>`).join('')}</section><section class="card" style="margin-top:22px"><h2>Garder ma progression</h2><p>Elle est sauvegardée dans ce navigateur. Exporte-la pour la transférer sur un autre appareil ou la protéger avant de vider les données du site.</p><div class="actions"><button id="export">Exporter ma progression</button><button class="quiet" id="import">Importer une sauvegarde</button><input hidden type="file" id="import-file" accept="application/json,.json"></div><details><summary>Installer et travailler hors connexion</summary><p>Ouvre le site en ligne une première fois et attends « Prêt hors connexion ». Sur Android : menu Chrome, Installer l’application ou Ajouter à l’écran d’accueil. Sur iPhone : Safari, Partager, Sur l’écran d’accueil.</p><p>Pour écouter hors connexion, télécharge une voix allemande dans les réglages de synthèse vocale du téléphone. Les fonctionnalités varient selon le navigateur. Les cours, cartes et exercices n’ont pas besoin de connexion après leur mise en cache.</p><p>Les informations restent sur cet appareil ; aucune synchronisation automatique entre téléphone et ordinateur.</p></details></section>`}
$('#main').innerHTML=html;}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function norm(s){return String(s).normalize('NFKC').toLocaleLowerCase('de').replace(/[.!?,;:]/g,'').replace(/\s+/g,' ').trim()}
function startQuiz(ids,mode){const qs=ids.length===1?U[ids[0]].quiz:ids.flatMap(i=>U[i].quiz.slice(0,mode==='global'?2:3));quiz={ids,qs:qs.map(q=>({...q,options:q.options?shuffled(q.options):undefined})),pos:0,correct:0,answer:'',checked:false,done:false,words:[]};view='exercise';location.hash=`exercise/${ids[0]}`;render()}
function quizBody(){const q=quiz;if(q.done){const score=Math.round(q.correct/q.qs.length*100);return `<span class="eyebrow">SÉANCE TERMINÉE</span><div class="result">${score} %</div><h2>${score>=80?'Bien joué !':'Continue, tu progresses.'}</h2><p>${q.correct} réponses correctes sur ${q.qs.length}. ${q.ids.length===1?(score>=80?'Cette unité est validée.':'Revois les explications puis réessaie.'):'Revois les unités qui t’ont posé problème.'}</p><div class="actions"><button id="retry">Réessayer</button><button class="quiet" data-go="courses/${unit}">Revoir le cours</button><button class="quiet" id="end-quiz">Terminer</button></div>`}
const item=q.qs[q.pos];return `<span class="eyebrow">QUESTION ${q.pos+1} / ${q.qs.length}</span><div class="progress"><div style="width:${q.pos/q.qs.length*100}%"></div></div><h2>${esc(item.prompt)}</h2>${item.type==='choice'?`<div class="options">${item.options.map(a=>`<button data-answer="${esc(a)}" ${q.checked?'disabled':''} class="${q.answer===a?'selected':''} ${q.checked&&a===item.answer?'correct':''} ${q.checked&&q.answer===a&&a!==item.answer?'wrong':''}">${esc(a)}</button>`).join('')}</div>`:item.type==='order'?`<p class="record" id="ordered">${esc(q.words.map(x=>x.word).join(' '))||'Choisis les mots dans l’ordre.'}</p><div class="wordbank">${(q.bank||(q.bank=shuffled(item.answer.split(' ')))).map((w,i)=>`<button data-word="${i}" ${q.checked||q.words.some(x=>x.i===i)?'disabled':''}>${esc(w)}</button>`).join('')}</div><button class="quiet" id="clear-words" ${q.checked?'disabled':''}>Recommencer l’ordre</button>`:`<label for="answer-input">Ta réponse en allemand</label><input id="answer-input" class="answer" value="${esc(q.answer)}" autocomplete="off" spellcheck="false" ${q.checked?'disabled':''}>`}${q.checked?`<div class="feedback ${q.ok?'':'bad'}"><strong>${q.ok?'Correct !':'À revoir.'}</strong><p>${esc(item.why)}</p></div><button id="next-question">${q.pos===q.qs.length-1?'Voir mon résultat':'Question suivante'}</button>`:`<div class="actions"><button id="check-answer">Vérifier</button></div>`}`}
function flashBody(){if(flash.pos>=flash.cards.length)return `<h1>Séance terminée</h1><section class="card"><h2>Tu as révisé ${flash.count} cartes.</h2><p>Les prochains rappels sont programmés. Les cartes difficiles restent dues aujourd’hui.</p><button id="end-flash">Retour aux révisions</button></section>`;const c=flash.cards[flash.pos];return `<h1>Retrouve le sens</h1><p class="sub">Carte ${flash.pos+1} / ${flash.cards.length} · ${esc(U[c.unit].fr)}</p><section class="card flash"><span class="eyebrow">ALLEMAND → FRANÇAIS</span><h2 lang="de">${esc(c.de)}</h2><button class="sound" data-say="${esc(c.de)}">Écouter</button>${flash.flipped?`<p class="translation">${esc(c.fr)}</p><div class="actions" style="justify-content:center"><button class="quiet" data-rate="0">À revoir</button><button data-rate="1">Je savais</button></div>`:`<div class="actions" style="justify-content:center"><button id="flip">Voir la traduction</button></div>`}</section><button class="quiet" id="end-flash">Arrêter la séance</button>`}
function startFlash(cards){if(!cards.length){toast('Aucune carte dans cette sélection. Découvre de nouvelles cartes.');return}flash={cards:[...cards],pos:0,flipped:false,count:0,repeated:new Set()};view='memory';location.hash='memory';render()}
function listenBody(){if(listening.pos>=U[unit].vocab.length)return `<h2>Écoute terminée : ${listening.correct}/8</h2><button id="start-listen">Réécouter cette unité</button>`;const v=U[unit].vocab[listening.pos];if(!listening.options)listening.options=shuffled([v.fr,...U[unit].vocab.filter(x=>x!==v).slice(0,2).map(x=>x.fr)]);return `<p>Phrase ${listening.pos+1}/8</p><button data-say="${esc(v.de)}">Écouter la phrase</button><div class="options">${listening.options.map(a=>`<button data-listen-answer="${esc(a)}" ${listening.checked?'disabled':''} class="${listening.checked&&a===v.fr?'correct':''}">${esc(a)}</button>`).join('')}</div>${listening.checked?`<div class="feedback ${listening.answer===v.fr?'':'bad'}"><strong>${listening.answer===v.fr?'Correct !':'À revoir.'}</strong><p lang="de">${esc(v.de)}</p><p>${esc(v.fr)}</p></div><button id="next-listen">Continuer</button>`:''}`}
function speak(text){if(!('speechSynthesis'in window)){toast('La synthèse vocale est indisponible dans ce navigateur.');return}const voices=speechSynthesis.getVoices(),de=voices.filter(v=>v.lang.toLowerCase().startsWith('de')),voice=de.find(v=>v.localService)||de[0];if(!voice){toast('Aucune voix allemande détectée. Installe une voix allemande dans les réglages du téléphone.');return}speechSynthesis.cancel();const s=new SpeechSynthesisUtterance(text);s.lang='de-DE';s.voice=voice;s.rate=.82;s.onerror=()=>toast('La voix ne peut pas lire cette phrase. Vérifie les réglages audio ou la connexion.');speechSynthesis.speak(s);save(true)}
if('speechSynthesis'in window){speechSynthesis.getVoices();speechSynthesis.addEventListener('voiceschanged',()=>speechSynthesis.getVoices())}
document.addEventListener('input',e=>{if(e.target.id==='answer-input'&&quiz)quiz.answer=e.target.value});
document.addEventListener('change',async e=>{if(e.target.id==='unit-select'){if(recorder?.state==='recording')recorder.stop();unit=Number(e.target.value);state.lastUnit=unit;listening=null;save();render()}if(e.target.id==='import-file'&&e.target.files[0]){try{const f=e.target.files[0];if(f.size>2000000)throw Error();const s=JSON.parse(await f.text());if(!valid(s))throw Error();state=s;save();render();toast('Progression importée.')}catch{toast('Sauvegarde invalide. Utilise un export de ce coach.')}}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset,id=b.id;
if(d.go){go(...d.go.split('/'));return}if(d.say){speak(d.say);return}if(d.tab){tab=d.tab;render();return}if(d.quiz!==undefined){unit=+d.quiz;startQuiz([unit]);return}if(d.bilan!==undefined){const start=+d.bilan*4+1;startQuiz([start,start+1,start+2,start+3]);return}if(d.flash!==undefined){unit=+d.flash;startFlash(allCards().filter(c=>c.unit===unit));return}
if(d.answer!==undefined){quiz.answer=d.answer;render();return}if(d.word!==undefined){quiz.words.push({i:+d.word,word:quiz.bank[+d.word]});quiz.answer=quiz.words.map(x=>x.word).join(' ');render();return}
if(d.rate!==undefined){const c=flash.cards[flash.pos],old=state.cards[c.key]||{interval:0},ok=d.rate==='1',interval=ok?(old.interval<1?1:old.interval<3?3:old.interval<7?7:old.interval<14?14:30):0;state.cards[c.key]={interval,due:Date.now()+interval*86400000,mastered:ok};if(!ok&&!flash.repeated.has(c.key)){flash.cards.push(c);flash.repeated.add(c.key)}flash.count++;flash.pos++;flash.flipped=false;save(true);render();return}
if(d.listenAnswer!==undefined){listening.checked=true;listening.answer=d.listenAnswer;if(d.listenAnswer===U[unit].vocab[listening.pos].fr)listening.correct++;save(true);render();return}
switch(id){case'check-answer':if(!quiz.answer.trim()){toast('Choisis ou écris une réponse.');break}quiz.ok=norm(quiz.answer)===norm(quiz.qs[quiz.pos].answer);quiz.checked=true;if(quiz.ok)quiz.correct++;save(true);render();break;
case'next-question':quiz.pos++;quiz.checked=false;quiz.answer='';quiz.words=[];quiz.bank=null;if(quiz.pos===quiz.qs.length){quiz.done=true;if(quiz.ids.length===1){const uid=quiz.ids[0];state.scores[uid]=Math.max(state.scores[uid]||0,Math.round(quiz.correct/quiz.qs.length*100));state.lastUnit=uid;save(true)}}render();break;
case'clear-words':quiz.words=[];quiz.answer='';render();break;
case'retry':startQuiz(quiz.ids,quiz.ids.length>4?'global':undefined);break;
case'end-quiz':quiz=null;render();break;
case'global-test':startQuiz(U.slice(1).map(x=>x.id),'global');break;
case'flip':flash.flipped=true;render();break;
case'end-flash':flash=null;render();break;
case'due-review':startFlash(dueCards());break;
case'new-review':startFlash(allCards().filter(c=>!state.cards[c.key]).slice(0,10));break;
case'start-listen':listening={pos:0,correct:0};render();break;
case'next-listen':listening.pos++;listening.options=null;listening.checked=false;render();break;
case'export':{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`deutsch-progression-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break}
case'import':$('#import-file').click();break;
case'install':if(installPrompt){await installPrompt.prompt();installPrompt=null}else{toast('Android : menu du navigateur → Installer. iPhone : Safari → Partager → Sur l’écran d’accueil.')}break;
case'record':try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('Enregistrement indisponible. Répète à voix haute ou utilise le dictaphone du téléphone.');break}stream=await navigator.mediaDevices.getUserMedia({audio:true});if(view!=='speak'){stream.getTracks().forEach(t=>t.stop());break}const chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType});stream.getTracks().forEach(t=>t.stop());if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(blob);if($('#recording')){$('#recording').innerHTML='<p>Ton enregistrement (reste sur cet appareil)</p><audio controls></audio>';$('#recording audio').src=recordUrl;$('#record').disabled=false;$('#stop-record').disabled=true}save(true)};recorder.start();$('#record').disabled=true;$('#stop-record').disabled=false;$('#recording').textContent='Enregistrement en cours…';}catch{toast('Microphone inaccessible. Autorise-le dans les réglages du navigateur.')}break;
case'stop-record':if(recorder?.state==='recording')recorder.stop();break;
}});
function route(){if(recorder?.state==='recording')recorder.stop();const [v,n]=(location.hash.slice(1)||'reader').split('/');if(view!==v){quiz=null;flash=null;listening=null}view=navs.some(x=>x[0]===v)?v:'home';if(view!=='reader'&&n!==undefined&&/^\d+$/.test(n)&&+n<U.length){unit=+n;state.lastUnit=unit;save();tab='understand'}render();window.scrollTo(0,0)}
window.addEventListener('hashchange',route);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
let offlineReady=false;function network(){ $('#network').textContent=offlineReady?(navigator.onLine?'Prêt hors connexion':'Hors connexion · cours disponibles'):(navigator.onLine?'Préparation du mode hors ligne…':'Hors connexion')}
window.addEventListener('online',network);window.addEventListener('offline',network);
if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;const worker=reg.active||reg.waiting||reg.installing;const channel=new MessageChannel();channel.port1.onmessage=e=>{offlineReady=e.data===true;network()};worker?.postMessage('CACHE_READY',[channel.port2]);}).catch(()=>{$('#network').textContent='Mode hors ligne indisponible'})}else{$('#network').textContent='Ouvre le site via son adresse web pour le mode hors ligne.'}route();

if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tools=[{name:'read_learning_progress',title:'Lire la progression',description:'Lire les scores et les révisions dues, sans modifier la progression.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {progress:pct(),scores:{...state.scores},dueCards:dueCards().length,streak:streak()}}},{name:'open_learning_unit',title:'Ouvrir une unité',description:'Ouvrir la leçon sélectionnée dans le coach ; ne valide pas la leçon.',inputSchema:{type:'object',properties:{unit:{type:'integer',minimum:0,maximum:12}},required:['unit'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isInteger(input.unit)||input.unit<0||input.unit>12)throw Error('Unité invalide');unit=input.unit;view='courses';tab='understand';state.lastUnit=unit;save();location.hash='courses/'+unit;render();return {unit,title:U[unit].title}}}];
 for(const t of tools){try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
