import json
from pathlib import Path
rows=[
('Start auf Deutsch','Premiers contacts',8,'Saluer, te présenter et épeler ton nom.','Ich signifie je ; du signifie tu. Pour vouvoyer, utilise Sie avec une majuscule. Une question avec wie (comment) ou woher (d’où) commence par ce mot, puis le verbe.','Ich heiße Oswaldo.|Je m’appelle Oswaldo.;Wie heißt du?|Comment t’appelles-tu ?;Woher kommst du?|D’où viens-tu ?;Ich komme aus Benin.|Je viens du Bénin.;Guten Tag!|Bonjour !;Auf Wiedersehen!|Au revoir !;Bitte.|S’il te plaît / s’il vous plaît.;Danke.|Merci.','ei se prononce /aɪ/ comme aï ; w se prononce /v/ ; ß se prononce /s/. Pour ich /ɪç/, laisse passer l’air entre la langue et le palais.','Hallo! Ich heiße Anna.|Salut ! Je m’appelle Anna.;Hallo Anna. Ich heiße Oswaldo.|Salut Anna. Je m’appelle Oswaldo.;Woher kommst du?|D’où viens-tu ?;Ich komme aus Benin. Und du?|Je viens du Bénin. Et toi ?;Ich komme aus Deutschland.|Je viens d’Allemagne.','Comment te présenterais-tu à un nouveau camarade ?','Ich ___ Oswaldo.|heiße|heißt|heißen'),
('Café d','Au café',16,'Commander, demander un prix et donner un numéro.','Au présent : ich komme, du kommst, er/sie kommt, wir kommen, ihr kommt, sie/Sie kommen. Sein (être) est irrégulier : ich bin, du bist, er ist, wir sind, ihr seid, sie sind. Dans une phrase déclarative simple, le verbe conjugué est en deuxième position.','Ich möchte einen Kaffee.|Je voudrais un café.;Was kostet das?|Combien cela coûte-t-il ?;Zahlen, bitte.|L’addition, s’il vous plaît.;Das macht drei Euro.|Cela fait trois euros.;ein Wasser|une eau;ein Tee|un thé;eins, zwei, drei|un, deux, trois;Meine Telefonnummer ist …|Mon numéro de téléphone est…','Dans Kaffee, l’accent porte sur fee. Dans les nombres comme einundzwanzig (21), on dit d’abord les unités : un et vingt.','Guten Tag. Was möchten Sie?|Bonjour. Que souhaitez-vous ?;Ich möchte einen Kaffee und ein Wasser.|Je voudrais un café et une eau.;Gern. Sonst noch etwas?|Volontiers. Autre chose ?;Nein, danke. Was kostet das?|Non, merci. Combien cela coûte-t-il ?;Das macht fünf Euro.|Cela fait cinq euros.','Commande deux boissons, puis demande le prix.','Du ___ aus Benin.|kommst|komme|kommen'),
('Im Sprachkurs','En cours de langue',30,'Nommer les objets et demander une explication.','Apprends chaque nom avec son article : der (masculin), die (féminin), das (neutre). Ein accompagne der et das ; eine accompagne die. Pour nier un nom indéfini : kein Buch, keine Tasche. Au pluriel : die Bücher, keine Bücher. Le pluriel doit être appris avec le nom.','das Buch, die Bücher|le livre, les livres;der Stift, die Stifte|le stylo, les stylos;die Tasche, die Taschen|le sac, les sacs;Was ist das?|Qu’est-ce que c’est ?;Das ist ein Buch.|C’est un livre.;Bitte sprechen Sie langsam.|Parlez lentement, s’il vous plaît.;Können Sie das wiederholen?|Pouvez-vous répéter cela ?;Ich verstehe das nicht.|Je ne comprends pas cela.','Pour ü, place la langue comme pour i et arrondis les lèvres comme pour u. Ö ressemble au son de peu. Ä ressemble souvent à è.','Was ist das auf Deutsch?|Comment dit-on cela en allemand ?;Das ist ein Wörterbuch.|C’est un dictionnaire.;Wie schreibt man das?|Comment cela s’écrit-il ?;Ich schreibe es an die Tafel.|Je l’écris au tableau.','Demande le nom allemand d’un objet puis demande de répéter.','Das ist ___ Tasche.|eine|ein|einen'),
('Städte – Länder – Sprachen','Villes, pays et langues',44,'Dire où tu habites et quelles langues tu parles.','Une question ouverte commence par un mot interrogatif : Wo wohnst du? Une question oui/non commence par le verbe : Wohnst du in Berlin? Pour parler d’un état passé : ich war, du warst, er/sie war, wir waren. La plupart des pays s’utilisent sans article : aus Benin, in Deutschland.','Ich wohne in Cotonou.|J’habite à Cotonou.;Ich spreche Französisch.|Je parle français.;Ich lerne Deutsch.|J’apprends l’allemand.;Wo liegt Berlin?|Où se trouve Berlin ?;im Norden|au nord;im Süden|au sud;im Osten|à l’est;im Westen|à l’ouest','L’intonation aide à distinguer une affirmation d’une question ; entraîne-toi sur Wohnst du in Berlin? Le ch de spreche est comme celui de ich.','Wo wohnst du?|Où habites-tu ?;Ich wohne in Cotonou.|J’habite à Cotonou.;Welche Sprachen sprichst du?|Quelles langues parles-tu ?;Ich spreche Französisch und lerne Deutsch.|Je parle français et j’apprends l’allemand.','Présente ta ville, ton pays et tes langues.','Gestern ___ ich in Berlin.|war|bin|sein'),
('Menschen und Häuser','Personnes et logements',58,'Décrire ton logement et tes affaires.','Les possessifs dépendent du nom : mein Tisch, meine Küche, mein Zimmer. L’accusatif marque notamment le complément direct : Ich habe einen Tisch. Au masculin, ein devient einen et der devient den ; au féminin et au neutre, les formes restent identiques. Trop se traduit par zu : Das Zimmer ist zu klein.','das Zimmer|la chambre / la pièce;die Küche|la cuisine;die Wohnung|l’appartement;der Tisch|la table;Mein Zimmer ist klein.|Ma chambre est petite.;Die Wohnung ist hell.|L’appartement est lumineux.;Ich habe einen Tisch.|J’ai une table.;Die Miete ist zu teuer.|Le loyer est trop cher.','Le ch de Küche se prononce comme dans ich ; celui de auch se produit plus en arrière dans la bouche.','Wie ist deine Wohnung?|Comment est ton appartement ?;Sie ist klein, aber hell.|Il est petit, mais lumineux.;Hast du eine Küche?|As-tu une cuisine ?;Ja, und ich habe zwei Zimmer.|Oui, et j’ai deux pièces.','Décris deux pièces de ton logement et un meuble.','Ich habe ___ Tisch.|einen|ein|eine'),
('Termine','Horaires et rendez-vous',82,'Dire l’heure et prendre rendez-vous.','Utilise um pour une heure (um neun Uhr), am pour un jour (am Montag), von … bis pour une plage horaire. Un verbe séparable se sépare dans une phrase principale : Ich stehe um sieben Uhr auf. Nicht nie une action ou une qualité : Ich arbeite heute nicht. Au passé, ich hatte signifie j’avais.','Wie spät ist es?|Quelle heure est-il ?;Es ist neun Uhr.|Il est neuf heures.;am Montag|lundi;um acht Uhr|à huit heures;Ich habe einen Termin.|J’ai un rendez-vous.;Ich stehe früh auf.|Je me lève tôt.;Entschuldigung, ich komme zu spät.|Excusez-moi, j’arrive en retard.;Passt es Ihnen am Dienstag?|Cela vous convient-il mardi ?','Dans spät, sp au début se prononce /ʃp/ comme chp. Dans stehen, st au début se prononce /ʃt/.','Wann haben Sie Zeit?|Quand êtes-vous disponible ?;Am Dienstag um zehn Uhr.|Mardi à dix heures.;Gut. Wir sehen uns am Dienstag.|Bien. Nous nous voyons mardi.;Vielen Dank. Bis Dienstag!|Merci beaucoup. À mardi !','Propose un rendez-vous avec un jour et une heure.','Der Termin ist ___ Montag.|am|um|aus'),
('Orientierung','Se repérer',98,'Indiquer un lieu et comprendre une direction.','Pour un lieu fixe, plusieurs prépositions prennent le datif : in dem Büro devient im Büro ; an dem Bahnhof devient am Bahnhof. Au datif : der devient dem, das devient dem, die devient der. Avec et bei prennent le datif : mit dem Bus, bei der Firma.','Wo ist der Bahnhof?|Où est la gare ?;Gehen Sie geradeaus.|Allez tout droit.;Dann nach links.|Puis à gauche.;nach rechts|à droite;Ich fahre mit dem Bus.|Je prends le bus.;im ersten Stock|au premier étage;Das Büro ist neben der Küche.|Le bureau est à côté de la cuisine.;Entschuldigung, wo ist Frau Müller?|Excusez-moi, où est Madame Müller ?','V peut se prononcer /f/ dans vier et /v/ dans les mots empruntés comme Video. Ne généralise pas une seule prononciation.','Entschuldigung, wo ist das Büro?|Excusez-moi, où est le bureau ?;Im zweiten Stock.|Au deuxième étage.;Wo ist die Treppe?|Où est l’escalier ?;Geradeaus, dann rechts.|Tout droit, puis à droite.','Demande où est la gare et explique un trajet simple.','Ich fahre mit ___ Bus.|dem|den|der'),
('Berufe','Métiers',112,'Parler de ton métier et de ta journée de travail.','Les verbes modaux accompagnent un infinitif à la fin : Ich kann Deutsch sprechen. Können exprime une capacité, müssen une obligation, wollen une volonté. Exemples : ich kann / du kannst ; ich muss / du musst ; ich will / du willst. Le métier après sein est généralement sans article : Ich bin Lehrer.','Was sind Sie von Beruf?|Quel est votre métier ?;Ich bin Ingenieur.|Je suis ingénieur.;Ich arbeite in einem Büro.|Je travaille dans un bureau.;Ich muss heute arbeiten.|Je dois travailler aujourd’hui.;Ich kann Deutsch sprechen.|Je sais parler allemand.;der Arzt, die Ärztin|le médecin, la médecin;der Lehrer, die Lehrerin|l’enseignant, l’enseignante;die Arbeit|le travail','Dans arbeiten, l’accent porte sur la première syllabe : AR-bei-ten. Distingue kann et können en écoutant la voyelle.','Was machen Sie beruflich?|Que faites-vous comme métier ?;Ich bin Ingenieur.|Je suis ingénieur.;Wann beginnen Sie?|Quand commencez-vous ?;Ich beginne um acht Uhr.|Je commence à huit heures.','Présente ton métier ou celui que tu souhaites exercer.','Ich kann Deutsch ___.|sprechen|spreche|sprichst'),
('Berlin sehen','Visiter Berlin',126,'Demander son chemin et raconter une visite.','Pour raconter une action passée, le parfait combine haben ou sein et un participe en fin : Ich habe Berlin besucht. Pour de nombreux déplacements : Ich bin nach Berlin gefahren. Pour la destination d’une ville : nach Berlin ; pour le lieu : in Berlin. Apprends le participe avec chaque verbe.','Ich möchte Berlin besuchen.|Je voudrais visiter Berlin.;Wie komme ich zum Bahnhof?|Comment aller à la gare ?;Nehmen Sie den Bus.|Prenez le bus.;Wo kann ich eine Fahrkarte kaufen?|Où puis-je acheter un billet ?;Ich habe Berlin besucht.|J’ai visité Berlin.;Ich bin nach Berlin gefahren.|Je suis allé à Berlin.;die Sehenswürdigkeit|le site touristique;der Stadtplan|le plan de la ville','Dans besucht, l’accent tombe sur sucht ; be- est une syllabe non accentuée. Dans Bahnhof, l’accent est au début.','Wie komme ich zum Museum?|Comment aller au musée ?;Nehmen Sie den Bus Nummer zehn.|Prenez le bus numéro dix.;Wo kann ich eine Fahrkarte kaufen?|Où puis-je acheter un billet ?;Am Automaten.|Au distributeur.','Demande comment aller à un musée et acheter un billet.','Ich ___ nach Berlin gefahren.|bin|habe|ist'),
('Ferien und Urlaub','Vacances',148,'Parler de vacances et d’un événement passé.','Au parfait, haben est fréquent : Ich habe gearbeitet. Sein s’utilise notamment pour des changements de lieu : Ich bin gefahren. Certains participes sont irréguliers : sehen → gesehen, fahren → gefahren. Les mois prennent im : im August. Ein Unfall signifie un accident.','Ich habe Urlaub.|Je suis en vacances / en congé.;Wir fahren im August.|Nous partons en août.;Ich reise mit meiner Familie.|Je voyage avec ma famille.;Ich habe ein Hotel gebucht.|J’ai réservé un hôtel.;Ich habe das Meer gesehen.|J’ai vu la mer.;Es gab einen Unfall.|Il y a eu un accident.;der Sommer|l’été;die Reise|le voyage','Le h de gesehen sépare les syllabes et n’est pas aspiré. Dans Urlaub, au forme une seule diphtongue /aʊ/.','Wann fährst du in Urlaub?|Quand pars-tu en vacances ?;Im August, mit meiner Familie.|En août, avec ma famille.;Wohin fahrt ihr?|Où allez-vous ?;Wir fahren ans Meer.|Nous allons à la mer.','Raconte un voyage en deux phrases au passé.','Ich habe das Meer ___.|gesehen|sehen|sehe'),
('Essen und trinken','Manger et boire',162,'Faire les courses et exprimer tes goûts.','Mögen exprime un goût : Ich mag Reis. Möchte permet de demander poliment : Ich möchte ein Brot. Pour une action appréciée, utilise gern : Ich esse gern Reis. Kein nie un nom : Ich esse kein Fleisch. Quantités : ein Kilo Tomaten, eine Flasche Wasser.','Ich möchte ein Brot.|Je voudrais un pain.;Ein Kilo Tomaten, bitte.|Un kilo de tomates, s’il vous plaît.;Wie viel kostet das?|Combien cela coûte-t-il ?;Ich esse gern Reis.|J’aime manger du riz.;Ich esse kein Fleisch.|Je ne mange pas de viande.;das Gemüse|les légumes;das Obst|les fruits;Guten Appetit!|Bon appétit !','Dans Gemüse, ü est arrondi et l’accent porte sur mü. Dans Obst, la voyelle initiale est longue.','Was möchten Sie?|Que souhaitez-vous ?;Ein Kilo Tomaten und ein Brot, bitte.|Un kilo de tomates et un pain, s’il vous plaît.;Sonst noch etwas?|Autre chose ?;Nein, danke. Wie viel kostet das?|Non, merci. Combien cela coûte-t-il ?','Achète trois produits et indique un aliment que tu aimes.','Ich esse ___ Fleisch.|kein|keine|nicht ein'),
('Kleidung und Wetter','Vêtements et météo',176,'Acheter un vêtement et parler du temps.','Les démonstratifs désignent un objet : dieser Pullover, diese Jacke, dieses Hemd. À l’accusatif masculin : diesen Pullover. Les verbes peuvent prendre le datif : Die Jacke gefällt mir (la veste me plaît). Pour la météo : Es regnet, es ist kalt.','Ich suche eine Jacke.|Je cherche une veste.;Welche Größe haben Sie?|Quelle taille faites-vous ?;Kann ich das anprobieren?|Puis-je essayer cela ?;Die Jacke gefällt mir.|La veste me plaît.;Das ist zu groß.|C’est trop grand.;Es regnet.|Il pleut.;Es ist kalt.|Il fait froid.;Heute ist es sonnig.|Aujourd’hui, il fait beau.','Dans Größe, ö est proche du son de peu ; ß est /s/. Dans Jacke, j se prononce /j/ comme y.','Ich suche eine Jacke.|Je cherche une veste.;Welche Größe haben Sie?|Quelle taille faites-vous ?;Größe M. Kann ich diese Jacke anprobieren?|Taille M. Puis-je essayer cette veste ?;Ja, natürlich.|Oui, bien sûr.','Demande une veste, une taille et la possibilité de l’essayer.','Die Jacke gefällt ___.|mir|ich|mein'),
('Körper und Gesundheit','Corps et santé',190,'Expliquer un symptôme et comprendre une consigne.','Pour une douleur : Mein Kopf tut weh (j’ai mal à la tête). Pour demander poliment : Trinken Sie Wasser! Au tutoiement : Trink Wasser! Sollen transmet une recommandation : Ich soll mich ausruhen. Utilise haben pour un symptôme : Ich habe Fieber.','Ich habe Kopfschmerzen.|J’ai mal à la tête.;Ich habe Fieber.|J’ai de la fièvre.;Mein Rücken tut weh.|J’ai mal au dos.;Seit gestern.|Depuis hier.;Ich brauche einen Termin.|J’ai besoin d’un rendez-vous.;Trinken Sie Wasser.|Buvez de l’eau.;Ruhen Sie sich aus.|Reposez-vous.;Gute Besserung!|Bon rétablissement !','Dans Schmerzen, sch correspond à ch français. Dans Kopf, p et f restent deux sons successifs.','Was fehlt Ihnen?|Qu’est-ce qui ne va pas ?;Ich habe Kopfschmerzen.|J’ai mal à la tête.;Seit wann?|Depuis quand ?;Seit gestern.|Depuis hier.;Ruhen Sie sich aus.|Reposez-vous.','Demande un rendez-vous et explique un symptôme et sa durée.','Mein Rücken ___ weh.|tut|tun|bist')]
units=[]
for i,r in enumerate(rows):
 title,fr,page,goal,grammar,vocab,pron,dialog,mission,cloze=r
 pairs=lambda s:[dict(zip(['de','fr'],x.split('|'))) for x in s.split(';')]
 d={'id':i,'title':title,'fr':fr,'page':page,'goal':goal,'grammar':grammar,'vocab':pairs(vocab),'pron':pron,'dialog':pairs(dialog),'mission':mission}
 prompt,answer,*wrong=cloze.split('|')
 qs=[{'type':'choice','prompt':prompt,'answer':answer,'options':[answer]+wrong,'why':grammar}]
 for j in range(3):
  v=d['vocab'][j]; others=[p['fr'] for k,p in enumerate(d['vocab']) if k!=j][:2]
  qs.append({'type':'choice','prompt':'Que signifie « '+v['de']+' » ?','answer':v['fr'],'options':[v['fr']]+others,'why':v['de']+' = '+v['fr']})
 v=d['vocab'][0];qs.append({'type':'text','prompt':'Traduis : '+v['fr'],'answer':v['de'],'why':'Réponse attendue : '+v['de']})
 v=next(p for p in d['vocab'] if len(p['de'].split())>=3 and '…' not in p['de']); qs.append({'type':'order','prompt':'Remets les mots dans l’ordre.','answer':v['de'],'why':v['fr']})
 d['quiz']=qs;units.append(d)
Path(__file__).with_name('content.js').write_text('window.UNITS='+json.dumps(units,ensure_ascii=False)+';',encoding='utf8')
units[8]['grammar']='Pour une destination : nach Berlin (vers Berlin), zum Bahnhof (à la gare), durch den Park (à travers le parc). Durch et une traversée exprimée par über prennent l’accusatif. Zu prend le datif : zu dem devient zum, zu der devient zur. Wollen exprime une intention : Ich will Berlin besuchen ; l’infinitif reste à la fin.'
units[8]['vocab'][4]={'de':'Ich will Berlin besuchen.','fr':'Je veux visiter Berlin.'}
units[8]['vocab'][5]={'de':'Wir gehen durch den Park.','fr':'Nous traversons le parc.'}
units[8]['quiz'][0]={'type':'choice','prompt':'Wir gehen durch ___ Park.','answer':'den','options':['den','dem','der'],'why':'Durch prend l’accusatif. Der Park devient den Park.'}
units[10]['grammar']='Pour la fréquence : jeden Tag (chaque jour), oft (souvent), manchmal (parfois), nie (jamais). Gern exprime le plaisir : Ich esse gern Reis. Pour comparer : gern → lieber → am liebsten ; gut → besser → am besten ; viel → mehr → am meisten. Welch- signifie quel et change selon le nom : welches Brot, welche Suppe.'
units[11]['grammar']+=' Un adjectif devant un nom prend une terminaison : Ich suche einen blauen Pullover, eine blaue Jacke, ein blaues Hemd. Après sein, l’adjectif ne change pas : Die Jacke ist blau.'
units[12]['grammar']+=' Dürfen exprime une permission : Darf ich Sport machen? (Puis-je faire du sport ?). À l’accusatif, les pronoms sont mich (me), dich (te), ihn (le), sie (la), es, uns (nous), euch (vous), sie/Sie. Exemple : Der Arzt untersucht mich.'
extras=[
 [('L’alphabet','A B C D E F G H I J K L M N O P Q R S T U V W X Y Z. Lettres supplémentaires : ä, ö, ü et ß. Pour épeler : Wie schreibt man das? Puis prononce chaque lettre, lentement.'),('Tutoyer ou vouvoyer','À un camarade : Wie heißt du? À une personne inconnue : Wie heißen Sie? Réponse : Ich heiße Oswaldo. Pour demander de l’aide : Bitte noch einmal (encore une fois, s’il vous plaît).')],
 [('Les nombres de 0 à 20','null, eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn, elf, zwölf, dreizehn, vierzehn, fünfzehn, sechzehn, siebzehn, achtzehn, neunzehn, zwanzig.'),('Compter jusqu’à 1 000','30 dreißig ; 40 vierzig ; 50 fünfzig ; 60 sechzig ; 70 siebzig ; 80 achtzig ; 90 neunzig ; 100 hundert ; 1 000 tausend. 21 = einundzwanzig ; 35 = fünfunddreißig. Un numéro de téléphone peut se lire chiffre par chiffre.')],
 [('Apprendre un nom correctement','Écris toujours article + nom + pluriel : das Buch / die Bücher. Les noms allemands commencent par une majuscule. Un mot composé prend le genre du dernier nom : das Kursbuch, car das Buch.'),('Nier un objet','Ist das ein Stift? Nein, das ist kein Stift. Ist das eine Tasche? Nein, das ist keine Tasche. Compare la terminaison au singulier et au pluriel.')],
 [('Présent et passé de sein','Aujourd’hui : Ich bin in Cotonou. Hier : Ich war in Cotonou. Autres formes : du warst ; er/sie/es war ; wir waren ; ihr wart ; sie/Sie waren.'),('Construire une question','Affirmation : Du wohnst in Berlin. Oui/non : Wohnst du in Berlin? Question ouverte : Wo wohnst du? Dans chaque cas, repère la position du verbe.')],
 [('Les possessifs','ich → mein ; du → dein ; er → sein ; sie → ihr ; wir → unser ; ihr → euer ; sie → ihr ; Sie → Ihr. Exemples : meine Wohnung, dein Zimmer, unser Haus.'),('Le complément direct','Ich habe einen Tisch, eine Lampe und ein Bett. Le masculin change à l’accusatif ; le féminin et le neutre gardent ici leur forme. Décris ton logement avec trois objets.')],
 [('Les jours et les heures','Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag. 8:30 = acht Uhr dreißig ; on peut aussi dire halb neun (une demi-heure avant neuf). 8:15 = Viertel nach acht ; 8:45 = Viertel vor neun.'),('La journée','Ich stehe um sieben Uhr auf. Ich arbeite von acht bis siebzehn Uhr. Ich hatte gestern einen Termin. Repère auf à la fin et hatte, le passé de haben.')],
 [('Le datif en pratique','der → dem ; die → der ; das → dem ; pluriel die → den, souvent avec -n au nom : mit den Kindern. Exemple : Das Buch liegt auf dem Tisch (lieu fixe).'),('L’ordre des étages','das Erdgeschoss : le rez-de-chaussée ; im ersten Stock : au premier étage ; im zweiten Stock : au deuxième étage. Demande : In welchem Stock ist das Büro?')],
 [('Capacité et obligation','Ich kann Deutsch sprechen. Ich muss heute arbeiten. Du kannst helfen. Du musst lernen. Le verbe modal est conjugué, le second verbe reste à l’infinitif en fin de phrase.'),('Possessif et négation à l’accusatif','Ich suche meinen Schlüssel. Ich habe keinen Computer. Pour un nom masculin complément direct, mein devient meinen et kein devient keinen.')],
 [('Dire où tu veux aller','Ich will zum Museum gehen. Wir gehen durch den Park. Gehen Sie an der Kirche vorbei (passez devant l’église). Apprends chaque préposition avec un exemple complet.'),('Vérifier une direction','Ist das weit? (Est-ce loin ?) Wie lange dauert das? (Combien de temps cela prend-il ?) Zu Fuß? (À pied ?) Répète la direction pour vérifier que tu as compris.')],
 [('Construire le parfait','Ich habe ein Hotel gebucht. Ich habe gearbeitet. Ich habe das Meer gesehen. Ich bin nach Berlin gefahren. L’auxiliaire est en deuxième position ; le participe ferme la phrase.'),('Les mois','Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember. Im Mai signifie en mai. Apprends aussi : die Familie, die Eltern, der Bruder, die Schwester.')],
 [('Exprimer ses préférences','Ich trinke gern Tee. Ich trinke lieber Wasser. Am liebsten trinke ich Kaffee. Pour la fréquence : Ich esse jeden Tag Reis. Ich esse nie Fleisch.'),('Quantités et recettes','ein Kilo Reis ; 500 Gramm Tomaten ; eine Flasche Wasser ; zwei Liter Milch. Pour lire une recette, cherche d’abord les quantités et les verbes : schneiden (couper), kochen (cuire), mischen (mélanger).')],
 [('Couleurs et tailles','rot (rouge), blau (bleu), grün (vert), gelb (jaune), schwarz (noir), weiß (blanc). Die Jacke ist blau. Ich suche eine blaue Jacke. Compare l’adjectif après sein et devant le nom.'),('La météo','Es regnet. Es schneit. Es ist warm. Es ist kalt. Die Sonne scheint. Entraîne-toi à décrire la météo du jour, puis le vêtement que tu portes.')],
 [('Les parties du corps','der Kopf (tête), der Rücken (dos), der Bauch (ventre), der Arm (bras), das Bein (jambe), die Hand (main), der Fuß (pied). Mein Bauch tut weh ; mes douleurs : Ich habe Bauchschmerzen.'),('Consignes et permission','Trinken Sie Wasser! Au tutoiement : Trink Wasser! Darf ich Sport machen? Le médecin : Der Arzt untersucht mich. Ces phrases servent à communiquer ; elles ne sont pas des conseils médicaux personnalisés.')]
]
for u,more in zip(units,extras):u['more']=[{'title':t,'text':s} for t,s in more]
for u in units:
 for q in u['quiz']:
  if q['type']=='choice' and q['prompt'].endswith('___') is False and q['why'].startswith('Au présent'):
   q['why']=u['grammar']
Path(__file__).with_name('content.js').write_text('window.UNITS='+json.dumps(units,ensure_ascii=False)+';',encoding='utf8')
